### ISSUE TITLE
For InceptionV3,  inception_v3.py and pre-trained model are different 

### ISSUE THREAD

**Issue by jbmpark** [soeaver/caffe-model#10]
For InceptionV3,  inception_v3.py and pre-trained model are different from each other.
Would you please update one of them?

Thank you for your work!

**Comment by soeaver** [comment]
@jbmpark 
I am very sorry for this mistake, the pre-train model on Baidu Cloud is the last version of any network include inception-v3\inception-v4\inception-resnet-v2. I' m to busy to update the python generator scripts, but I will fix it ASAP.
