### ISSUE TITLE
inception_v4测试错误

### ISSUE THREAD

**Issue by yja1** [soeaver/caffe-model#12]
您好，我想请您给我看下我训练的有什么问题。
训练数据1万个类别，人脸图像
训练prototxt:在您给出的连接下载的inception_v4
[3train_val_inception_v4.txt](https://github.com/soeaver/caffe-model/files/1009886/3train_val_inception_v4.txt)
[deploy_v4_1.txt](https://github.com/soeaver/caffe-model/files/1009887/deploy_v4_1.txt)

训练过程没有什么问题，虽然我训练过程的val集只有8个图像，输出accuracy增长到0.91

但是我测试的时候下载的
[evaluation_cls.txt](https://github.com/soeaver/caffe-model/files/1009893/evaluation_cls.txt)
不管输入哪个人脸图，输出分数最大值序号都是7320. 不知道哪里弄错了。我尝试改deplot_v4_1.txt的BatchNorm层use_global_stats: false 输出分数最大值序号都是248.

非常感谢您的回答！

**Comment by soeaver** [comment]
测试的时候要用use_global_stats: true
你在训练的时候数据处理只减了128均值，没有除方差，所以你在测试的时候std应该设置为std = np.array([1.0, 1.0, 1.0])。

**Comment by yja1** [comment]
还真是，我训练的prototxt只写了mean_value 忘记了scale: 0.0078125
除以方差会好一点还是不除以会好一点呢？还是跟数据有关呢？

**Comment by soeaver** [comment]
你可以自己算一下自己的数据集的均值方差， 不过一般来讲影响不大

**Comment by kli-casia** [comment]
@yja1  你的solver 的prototxt能不能发一下？谢谢

**Comment by yja1** [comment]
@kli-nlpr 
net: "3train_val_inception_v4.prototxt"
test_iter: 4000
test_interval: 10100
display: 100
base_lr: 0.01
lr_policy: "multistep"
#stepsize: 100000
stepvalue: 280000
stepvalue: 350000

gamma: 0.1
max_iter: 400000
momentum: 0.9
weight_decay: 0.0002
snapshot: 10000
solver_mode: GPU

**Comment by kli-casia** [comment]
@yja1  thanks
