### ISSUE TITLE
Message type "caffe.PoolingParameter" has no field named "ceil_mode"

### ISSUE THREAD

**Issue by yunren** [soeaver/caffe-model#14]
Hi！
there is an error when I finetune my task using your prototxt of  ResneXt-50 net.
Protobuf : Error parsing text-format caffe.NetParameter: 104:14: Message type "caffe.PoolingParameter" has no field named "ceil_mode". . at ..\src\google\protobuf\text_format.cc Line 274

Would you like to help me how to solve the problem?

**Comment by soeaver** [comment]
please check this https://github.com/BVLC/caffe/pull/3057/files

**Comment by yunren** [comment]
thanks for your help. I know the reason why the error appears. because I use the windows version of caffe which has no parameter named "ceil_mode".
