### ISSUE TITLE
Difference between Inception V4 deploy.prototext and .caffemodel on Baidu Cloud

### ISSUE THREAD

**Issue by JoshuaCWebDeveloper** [soeaver/caffe-model#15]
First of all, thank you so much for sharing your work on this repo!

I saw your response to #10 where you say the Python scripts are likely out of date. 

However, I obtained the model and weights from the Baidu Cloud package, and I believe that the network in the Inception V4 `deploy.prototxt` is different than the one in the `.caffemodel`. When I try and run this model, I get the following error:
```
Check failed: target_blobs.size() == source_layer.blobs_size() (5 vs. 3) Incompatible number of blobs for layer conv1_3x3_s2_bn
```
I originally got this error in DIGITS when running a train_val.prototxt I created from the `deploy.prototxt` file; however I can reproduce it with the following line of code in Python:
```
 caffe.Net('deploy_inception_v4.prototxt', 'inception_v4.caffemodel', caffe.TEST)
```

My interpretation of this error is that there is a conflict between the two files, but I'm pretty new to Caffe so I could be wrong. Can you confirm that the `deploy.prototxt` doesn't match the `.caffemodel`? If so, could you possibly share the `deploy.prototxt` that _does_ match?

Thank you again.

**Comment by JoshuaCWebDeveloper** [comment]
I'm also getting the same error for ` conv1_3x3_s2_bn` in the inception_resnet_v2 model.

**Comment by soeaver** [comment]
I think this error is caused by DIGITS. All models support only caffe.

**Comment by JoshuaCWebDeveloper** [comment]
@soeaver Thanks for responding.
1. DIGITS runs on Caffe (albeit a modified version)
2. And (as described in the original post), this error also happens when running Caffe in Python.

**Comment by shicai** [comment]
Compared with official caffe, digits caffe uses a different implementation of BN layers.
Please check their source codes.

**Comment by JoshuaCWebDeveloper** [comment]
@shicai Thanks for the tip.

I have confirmed that the Python call described in the original issue does in fact successfully execute on a vanilla version of Caffe (rc5 tag).

Interestingly though, the call did output these two lines at the end:
```
I0605 16:55:04.100076  3709 upgrade_proto.cpp:77] Attempting to upgrade batch norm layers using deprecated params: inception_v4.caffemodel
I0605 16:55:04.100229  3709 upgrade_proto.cpp:80] Successfully upgraded batch norm layers using deprecated params.
```
Don't know if that is related or not.

I'll have to investigate how DIGITS Caffe uses batch norm layers.
