### ISSUE TITLE
Train with inception_v4_train_test.prototxt:  Check failed: top_shape[j] == bottom[i]->shape(j)

### ISSUE THREAD

**Issue by honeytidy** [soeaver/caffe-model#17]
That is the error message:
> I0613 10:06:28.511732 16295 net.cpp:84] Creating Layer inception_stem3
> I0613 10:06:28.511740 16295 net.cpp:406] inception_stem3 <- inception_stem3_3x3_s2
> I0613 10:06:28.511749 16295 net.cpp:406] inception_stem3 <- inception_stem3_pool
> I0613 10:06:28.511759 16295 net.cpp:380] inception_stem3 -> inception_stem3
> F0613 10:06:28.511782 16295 concat_layer.cpp:42] Check failed: top_shape[j] == bottom[i]->shape(j) (25 vs. 26) All inputs must have the same shape, except at concat_axis.
>

**Comment by soeaver** [comment]
please view https://github.com/soeaver/caffe-model/issues/11
