### ISSUE TITLE
Size of images in validation set

### ISSUE THREAD

**Issue by kmonachopoulos** [soeaver/caffe-model#18]
I see that the validation images are in size 500x375. In the evaluation python script you can set one value at the base_size variable, but as you can see the val images are not square, how can I use 'evaluation_cls.py' ? it throws error :

> Check failed: top_shape[j] == bottom[i]->shape(j) (12 vs. 13) All inputs must have the same shape, except at concat_axis.

Thanks.

**Comment by soeaver** [comment]
In the evaluation python script, we evaluate the accuracy on the single crop_size*crop_size center crop from an image whose shorter side is base_size. 
And please view https://github.com/soeaver/caffe-model/issues/11. to solve this error.
