### ISSUE TITLE
训练inception_resnet_v2出现错误

### ISSUE THREAD

**Issue by clscy** [soeaver/caffe-model#26]
你好。我用您提供的deploy_inception_resnet_v2.prototxt网络生成train_test.prototxt后训练的时候，
[inception_resnet_v2_solver.prototxt.txt](https://github.com/soeaver/caffe-model/files/1137974/inception_resnet_v2_solver.prototxt.txt)
[inception_resnet_v2_train_test.prototxt.txt](https://github.com/soeaver/caffe-model/files/1137985/inception_resnet_v2_train_test.prototxt.txt)
出现了如下错误：
concat_layer.cpp:42] Check failed: top_shape[j] == bottom[i]->shape(j) (10 vs. 11) All input
s must have the same shape, except at concat_axis.
请问该如何修改网络参数。
谢谢

**Comment by soeaver** [comment]
crop size problem.
please view https://github.com/soeaver/caffe-model/issues/11

**Comment by clscy** [comment]
非常感谢。 @soeaver
