### ISSUE TITLE
为什么用inception-resnet-v2训练ｆａｓｔｅｒ－rcnn的时候去掉BN层，而且卷积层的bias_term设为false？

### ISSUE THREAD

**Issue by xialuxi** [soeaver/caffe-model#27]

**Comment by xialuxi** [comment]
是因为有了预训练模型，所以就没有加了吗？

**Comment by soeaver** [comment]
Please view https://github.com/soeaver/caffe-model/tree/master/det#object-detection-performance-on-pascal-voc again.
**And, in order to facilitate the non-Chinese users, please use English for any issue.**

**Comment by xialuxi** [comment]
thanks
