### ISSUE TITLE
Is your inception_v3.deploytxt different from official paper?

### ISSUE THREAD

**Issue by clscy** [soeaver/caffe-model#29]
Hi, the official paper said that Inception modules where each 5 × 5 convolution is replaced by two 3 × 3 convolution. So why you design your network by 5 × 5 convolution? Doesn't it have other special important reason?
Thanks.

**Comment by soeaver** [comment]
You mean the inception-v1 (googlenet)?  In tensorflow-model/slim, the original implementation also adopt 5x5 conv, and the two 3x3 conv design is appeared later in inception-v2.

**Comment by clscy** [comment]
The paper "Rethinking the Inception Architecture for Computer Vision" gave the structure of inception_v3 in page six. And it said the first three inception were designed as in figure 5 in this paper. The figure 5 said Inception modules where each 5 × 5 convolution was replaced by two 3 × 3 convolution. Am I confused of inception_v1, inception_v2 and inception_v3?
Thanks.

**Comment by soeaver** [comment]
@clscy we follow the tf implementation of inception-v3

**Comment by clscy** [comment]
OK，Thanks.
