### ISSUE TITLE
fail in finetuning xception with caffe

### ISSUE THREAD

**Issue by chenbinghui1** [soeaver/caffe-model#30]
It throws an error that "check failed: status==CUDNN_STATUS_SUCCESS(4 VS. 0) CUDNN_STATUS_INTERNAL_ERROR"
My cuda is cuda8.0 and cudnn is v5
Can someone help me?

**Comment by soeaver** [comment]
Large group conv layer does not support well in cudnn, you can use  **engine: CAFFE** in the conv layers with group like this(https://github.com/shicai/MobileNet-Caffe).

But, we recommend using mobilenet or xception with py-RFCN-priv(https://github.com/soeaver/py-RFCN-priv), which supports depth-wise conv layer.

**Comment by chenbinghui1** [comment]
@soeaver Tanks! It does work.
