### ISSUE TITLE
Check failed: error == cudaSuccess (74 vs. 0)  misaligned address

### ISSUE THREAD

**Issue by chenbinghui1** [soeaver/caffe-model#31]
when I fine-tune the inceptionv4 model with batch size 2 or more than 2 (initializes  Train and Test net together, batch size 2 for Train net and batch size 1 for Test net), It throws this above error. Only when the batch size for Train net is 1, it works well. But when i only use the TEST net (e.g. when extracting features), the batch size can be 20. What happens. Does someone know that?

**Comment by chenbinghui1** [comment]
the image size is 331x331

**Comment by soeaver** [comment]
how much GPU memory do you have?

**Comment by chenbinghui1** [comment]
@soeaver 12G memory.

**Comment by soeaver** [comment]
@chenbinghui1 I am sorry that I don't know why the error happens. I also use the 12GB mem GPU, and I can finetune the inception-v4 model with batch_size=12 crop_size=299.

**Comment by zhanglonghao1992** [comment]
when I  fine-tune the resnext-50-32*4d it throws the same error. It only allows me to use batch_size 1for training. My GPU memory is 24G. @soeaver

**Comment by zhanglonghao1992** [comment]
@chenbinghui1 Same error，do u know why？Something wrong with his pretrain model？I cant find other inceptionv4 or resnext pretrain model in GitHub..

**Comment by chenbinghui1** [comment]
@zhanglonghao1992 sorry! I have not find out the reason. But you can try to use a smaller input size, e.g. 299 or 224.

**Comment by zhanglonghao1992** [comment]
@chenbinghui1  My input size is 256,crop size is 224,sitll get the error..
You use the smaller input size and solve this problem?

**Comment by chenbinghui1** [comment]
@zhanglonghao1992 yes I can fine-tune the inceptionv4 with input size (IS) 299 and batch size (BS) 10, and resnext101_32x4d with IS 320 and BS 4.

**Comment by zhanglonghao1992** [comment]
@chenbinghui1 That means when we use some big batch size such as 32 or 64 it will throw this error?
But I think batch size  is crucial  for the cls task, a small batch size may not get the best result..

**Comment by soeaver** [comment]
For cls task, I suggest to use mxnet or pytorch

**Comment by chenbinghui1** [comment]
@zhanglonghao1992 you can set iter_size in solver.prototxt to enlarge the batch size, e.g. final BS= BS*iter_size

**Comment by zhanglonghao1992** [comment]
@chenbinghui1 Thats really a good solution，3q！
