### ISSUE TITLE
xception 224x224 can not run

### ISSUE THREAD

**Issue by KeyKy** [soeaver/caffe-model#32]
I get the following error:
```
xception2_elewise <- xception2_match_conv
xception2_elewise <- xception2_pool
xception2_elewise -> xception2_elewise
Check failed: bottom[0]->shape() == bottom[i]->shape() bottom[0]: 1 256 28 28 (200704), bottom[1]: 1 256 27 27 (186624)
```

**Comment by soeaver** [comment]
The input size of xception is like inception-v3/v4, you should use 299*299 input

**Comment by KeyKy** [comment]
@soeaver 299x299(base_size=320) and 395x395(base_size=395) crop size for inception. base_size is 320x320 or 320 is using resize short?

**Comment by soeaver** [comment]
320 for short side
