### ISSUE TITLE
关于detection中的multiscale training 和testing问题

### ISSUE THREAD

**Issue by zhanglonghao1992** [soeaver/caffe-model#33]
请问该如何实现多尺度的训练和测试？
我之前将config文件中的train.scales参数从单一的600改为（200,300,400,500,600,700,800），训练可以进行，但是测试时test.scales修改为多尺度后会报错，请问是原版不支持多尺度测试吗？
还有一个问题就是除了修改图片尺度外，是否需要调整anchor大小？原有的9种anchor是否只是针对600尺寸设计的，当进行多尺度训练时是否应该引入更小和更大尺寸的anchor呢？

**Comment by soeaver** [comment]
The official faster and rfcn didn't support multi-scale testing, you should write a script to perform that.
And normally, for multi-scale training we do not need to modify the anchor scales and  ratios. The anchor setting usually depends on dataset.

**Comment by zhanglonghao1992** [comment]
3q ：）
