### ISSUE TITLE
In DenseNet, there should not have pad=1 in pool1 in caffe version

### ISSUE THREAD

**Issue by xmyqsh** [soeaver/caffe-model#34]
Hi,
Your implementation of DenseNet use pad=1 as in the [original torch version](https://github.com/liuzhuang13/DenseNet/blob/master/models/densenet.lua#L107)

But the implementation of pooling is different between the caffe and torch, the former use `ceil((imsize + 2*pad - kernel) / stride) + 1` and the latter use `floor((imsize + 2*pad - kernel) / stride) + 1`

So, your feature map is different with the paper.
Just remove the pad=1 in pool1 will be ok.

**Comment by soeaver** [comment]
@xmyqsh 
I use **ceil_mode: false**(https://github.com/BVLC/caffe/pull/3057/files) in the caffe version pooling layer. So, the feature map is exactly the same with torch's.

For example:

layer {
  name: "pool1"
  type: "Pooling"
  bottom: "conv1"
  top: "pool1"
  pooling_param {
    pool: MAX
    kernel_size: 3
    stride: 2
    pad: 1
    ceil_mode: false
  }
}

**Comment by xmyqsh** [comment]
Good  ceil_mode!
