### ISSUE TITLE
target_blobs.size() == source_layer.blobs_size() (2 vs. 1)

### ISSUE THREAD

**Issue by jacco09** [soeaver/caffe-model#36]
I use the resnext101-64x4d(R-FCN) to do det. And the pre-trained model is resnext101-64x4d-merge.caffemodel.
but it report the error:
Check failed: target_blobs.size() == source_layer.blobs_size() (2 vs. 1) Incompatible number of blobs for layer conv1
is my pre-trained model not suit for the resnext101-64x4d 
could you help me?

**Comment by soeaver** [comment]
I have fixed the bug, please download the newest https://github.com/soeaver/caffe-model/tree/master/det/rfcn/models/pascal_voc/resnext101-64x4d
And, all the det prototxt files apply to merge bn&scale caffemodels (https://github.com/soeaver/caffe-model/tree/master/det#1-original-faster-rcnn-training-on-voc-20072012-trainval-and-testing-on-voc-2007-test)

**Comment by jacco09** [comment]
Thanks.
And what's more,I want to apply densenet for det, have you tried it ?? My program's result of applying densenet for det (basing on R-FCN) is not good.

**Comment by soeaver** [comment]
I have tried faster rcnn densenet201 for det, but it costs too much GPU memory. And I didn't found significant improvment.
