### ISSUE TITLE
The wrn prototxt file in cls

### ISSUE THREAD

**Issue by zhanglonghao1992** [soeaver/caffe-model#37]
deploy_wrn50-2.prototxt doesn't seems like the real ‘wrn’ network，its just the nomal resnet-50 i
think..

**Comment by soeaver** [comment]
Check carefully, it is really wider than resnet50

**Comment by zhanglonghao1992** [comment]
@soeaver WRN use dropout between two 3*3 conv in a  residual block, but in this prototxt I just see nomal bottleneck conv with bn.

**Comment by soeaver** [comment]
Just for small dataset, please read the paper and source code again.

**Comment by zhanglonghao1992** [comment]
@soeaver  I see.. Its quite interesting that two 3*3 suits small datases well but Imagenet needs bottleneck..
