### ISSUE TITLE
range of input values for the models

### ISSUE THREAD

**Issue by adwardlee** [soeaver/caffe-model#41]
Hi soeaver,

What is the range of input values for inception-resnet and resnet? Could you please tell me which one is right? [0,255], [0,1] or [-1,1]? Thanks.

**Comment by soeaver** [comment]
0, 255

**Comment by adwardlee** [comment]
Thanks for your quick reply!

**Comment by adwardlee** [comment]
Sorry for reopening. The mean value is [104,117,123] or 128? Thanks.

**Comment by soeaver** [comment]
![image](https://user-images.githubusercontent.com/8629203/29976423-8bd72f74-8f6c-11e7-9503-5ee291b218b5.png)

**Comment by adwardlee** [comment]
Thank you very much!
