### ISSUE TITLE
Would you mind share resnet34?

### ISSUE THREAD

**Issue by 408550969** [soeaver/caffe-model#44]
I  training resnet34 for myself ，but the  accuracy is only 62.2（top-1）. the picture size is 224*224.
Would you mind share resnet34?

**Comment by 408550969** [comment]
请问你们的data argument都用的什么？还有caffe默认是center crop吗？

**Comment by soeaver** [comment]
I am sorry, we didn't train the resnet34. And usually, we train the imagenet  cls model on pytorch, like resnet18-priv or resnext26-32x4d-priv.

**Comment by 408550969** [comment]
Thanks
