### ISSUE TITLE
Difference between inception-v4-3x3 model and inception-v4 model about RFCN

### ISSUE THREAD

**Issue by GT9505** [soeaver/caffe-model#46]
Hi,soeaver. I notice when you use RFCN train inception v4 model, you trained two kind of model: inception v4 and inception v4 3x3. Could you tell me the difference between inception v4 and inception v4 3x3.

**Comment by GT9505** [comment]
Hi,soeaver. I notice when you use RFCN train inception v4 model, you trained two kind of model: inception v4 and inception v4 3x3. Could you tell me the difference between inception v4 and inception v4 3x3.

**Comment by soeaver** [comment]
I replace the 1x3 and 3x1 conv with 3x3 conv in inception-v4 for dilated conv, that's the inception-v4-3x3

**Comment by GT9505** [comment]
When I try to use RFCN train inception v4 with VOC0712 trainval, I only get 77.33mAP on VOC2007 test. I notice the solver.prototxt and rfcn_end2end_ohem.yml you provided is used to train ResNet-101 v2. Is there difference about the two files when training the two kind of models

**Comment by soeaver** [comment]
There is no difference between the two files.

**Comment by GT9505** [comment]
Thanks a lot!
