### ISSUE TITLE
What is CPANet?

### ISSUE THREAD

**Issue by terrychenism** [soeaver/caffe-model#47]
Could you provide Context Pyramid Attention Network paper as reference? Thanks!

**Comment by StarStyleSky** [comment]
Is there the paper aboat CPANet?thanks!

**Comment by soeaver** [comment]
@terrychenism @StarStyleSky Thanks for your attention.
CPANet is our recently work, we are still doing more experiments. The paper will be released as soon as possible.

**Comment by StarStyleSky** [comment]
thanks for your reply@soeaver

**Comment by terrychenism** [comment]
Great! How about the multi-scale testing result of CPANet?

**Comment by acgtyrant** [comment]
Still no released?
