### ISSUE TITLE
How to use deformable_psroi_pooling layer？

### ISSUE THREAD

**Issue by shengzhang90** [soeaver/caffe-model#50]
Could you please show an example in prototxt format about how to use the deformable_psroi_pooling_layer? Thank you very much.

**Comment by soeaver** [comment]
[deformpsroi.txt](https://github.com/soeaver/caffe-model/files/1367388/deformpsroi.txt)

**Comment by shengzhang90** [comment]
Thank you very much! But I don't know the meaning of parameters: sample_per_part, no_trans, part_size, trans_std?

**Comment by soeaver** [comment]
You need to read the code of https://github.com/msracver/Deformable-ConvNets

**Comment by shengzhang90** [comment]
Get! Thank you very much!
