### ISSUE TITLE
Use faster-rcnn training DPN network by alt 

### ISSUE THREAD

**Issue by zhujiapeng** [soeaver/caffe-model#55]
Hi,
I am trying to training dpn network using faster-rcnn by 4-steps method, the training process is normal, both the rpn loss and fast-rcnn loss are reducing. But during the test, the result is very poor, Have you used 4-steps to training dpn network?

**Comment by soeaver** [comment]
I am sorry, I only used the end2end training procedure.

**Comment by zhujiapeng** [comment]
Another question, I am trying to use end2end method to training DPN networks, when I use the dpn92-merge.caffemodel to initial the network, the output of some loss are very large(in my case are loss_bbox=210.396, loss_cls=87.0391, rpn_cls_loss=0.7288, rpn_loss_bbox=0.8088), So It made me can't training the network, but when I use the dpn92.caffemodel to initial the network, the loss is normal and decreasing by the time. But the test result is poor... Did you meet such question in your training ?  And I think this is also the answer of my first question, in which I also initial the network using dpn92.caffemodel

**Comment by soeaver** [comment]
I think you should check that your train.prototxt is also merge bn-scale or not?

**Comment by zhujiapeng** [comment]
@soeaver  I used the network on your github 'det/faster_rcnn/models/pascal_voc/dpn92/faster_voc_dpn92-merge.prototxt'  initial weights are 'dpn92-merge.caffemodel' to training using end2end method. Got the loss I described in last question.

**Comment by soeaver** [comment]
Sorry, so that nothing I can help.
