### ISSUE TITLE
train_val and solver for inception v4

### ISSUE THREAD

**Issue by sebastiangonsal** [soeaver/caffe-model#59]
Can you share prototxt files for train_val.prototxt and solver.prototxt for inception v4 model

**Comment by soeaver** [comment]
the model is converted from tensorflow, I didn't train the network on caffe

**Comment by xkorat** [comment]
how to convert it from tensorflow checkpoints to caffe? does it still keep same accuracy with original tensorflow top1 and top5 error rate?

**Comment by soeaver** [comment]
If there is no error in the process of conversion, the accuracy will not be lost.
