### ISSUE TITLE
Is there a python script to generate resnext network?

### ISSUE THREAD

**Issue by pustar** [soeaver/caffe-model#8]
You claimed resnext here, however I didn't see a python script to generate resnext network. Can you share such one script to generate resnext?

**Comment by soeaver** [comment]
I am vry sry to forget to upload resnext generator script. I have fixed issue. 
Thanks for reminding！

**Comment by bettyeats** [comment]
How to use resnext.py to generate a resnext caffemodle file? Is there any method caffe offered? Thank U!
