### ISSUE TITLE
One question on inception-v3 MXNet model

### ISSUE THREAD

**Issue by handong1587** [soeaver/caffe-model#9]
First I want to thank your great job and sharing this comprehensive evaluation.
I am not clear if it is appropriate to post this question here but I am very curious that, in the inception-v3 MXNet page [https://github.com/dmlc/mxnet-model-gallery/blob/master/imagenet-1k-inception-v3.md](https://github.com/dmlc/mxnet-model-gallery/blob/master/imagenet-1k-inception-v3.md), 
I downloaded its model file inception-v3.tar.gz, and I can see that in Inception-7-symbol.json, the "FullyConnected" op "fc1" has a "num_hidden" with **1008**, which I thought should be **1000**. 
And actually @soeaver already convert it to a caffemodel with "fc1" layer with num_output of 1000.
I am new to MXNet and just want to know what happen to MXNet's "fc1", thanks ~

**Comment by soeaver** [comment]
@handong1587 Thank you for your attention.
As far as I am concerned, the MXNet version inception-v3 model is also converted from tensorflow. The original model has 1008 hidden layer neurons as classifier, bus it seems like the last 8 neurons are useless, so I remove them when I convert it to caffe with no loss of accuracy.

**Comment by handong1587** [comment]
@soeaver Got it. Thanks for your reply!
